# Default values for helm-website-boilerplate.

replicaCount: 1

image:
  repository: securityunion/nextjs-demo
  pullPolicy: Always
  tag: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 4444

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: my-website.local
      path: /

resources: {}
